
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/nutmai
    username: nutmai
    password: nutmai
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect